name: HoneyCore
main: org.scorpion.HoneyCore
version: 2.1.0
api-version: 1.20
author: NightDev401 (Lukas)
commands:
  gamemode:
  gm:
  heal:
  setspawn:
  spawn:
  teleport:
  tp:
  rtp:
  tpa:
  tpaccept:
  tpdeny:
  tpahere:
  workbench:
  wb:
  craft:
  sethome:
  home:
  delhome:
  ec:
  enderchest:
  back:
  warp:
  setwarp:
  delwarp:
  fly:
  sun:
  night:
  day:
  rain:
  kick:
  ping:
  ui:
  glow:
  seen:
  ban:
  kill:
  broadcast:
    aliases: bc
  sudo:
  god:
  hat:
