name: HoneyCore
main: org.scorpion.HoneyCore
version: 1.0
api-version: 1.17
author: NightDev401 (Lukas)
commands:
  gamemode:
  gm:
  heal:
  setspawn:
  spawn:
  teleport:
  tp:
  rtp:
  tpa:
  tpaccept:
  tpdeny:
  tpahere:
  workbench:
  wb:
  craft:
  sethome:
  home:
  delhome: